### ISSUE TITLE
[DX] Insert dispatcher inside entities no matter what and log a warning

### ISSUE THREAD

**Issue by Nek-** [swagindustries/doctrine-domain-events#5]
Today if you instantiate a "DomainModel" this way:

```
$some = new Thing();
```

No dispatcher is automatically inserted inside the object. It may lead to a headache in understanding what's wrong (besides it's actually pretty obvious 😅 ).

A fix to that could be to inject the dispatcher in the model on flush no matter what, but to log a warning and add a special warning part in the profiler.

**Comment by mcsky** [comment]
After discussion, we decided that insert the dispatcher no matter what can lead to dangerous and complex scenarios. 

So now the behaviour is to throw an exception if the kernel is in debug mode at doctrine flush time
